### ISSUE TITLE
Return value of single returned document using Monk / Mongo

### ISSUE THREAD

**Issue by etanb** [etanb/koa-blog#1]
In my routes file, I'm trying to get the value of my post_counter document. How do I return the value to use? 

var post_counter = posts.findOne( { tracker: "post_counter" }, function (e, counter) {
    return counter.counter
  })

It's only returning a function not the value. @lambtron Help?

**Comment by lambtron** [comment]
The anonymous function that you are passing is a callback function and won't return the `counter.counter` in time. Therefore `post_counter` is going to be `undefined`.

You should use generators, because this is why you are using koa :). Use the `co-monk` [module](https://www.npmjs.com/package/co-monk/) like this:
https://github.com/lambtron/ladder/blob/master/server/lib/user.js#L7

And then you can just

```
var post = yield post.findOne({ tracker: "post_counter" });
var post_counter = post.counter;
```

Look at my repos for more examples.

**Comment by etanb** [comment]
Perfect! thank you sir.
